# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "pry", "~> 0.12.2"
gem "colorize", "~> 0.8.1"
gem "rest-client", "~> 2.0"
