# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
zoo_portraits = [
  'https://www.zooportraits.com/wp-content/uploads/2019/02/Golden-tiger-Panthera-tigris.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2019/02/Yellow-spotted-rock-hyrax-Heterohyrax-brucei.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/11/Black-And-White-Hawk-Eagle-Spizaetus-melanoleucus-2.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/11/Domestic-sheep-Ovis-aries-2-2.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/11/Emperor-penguin-Aptenodytes-forsteri-1.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/07/Crowned-lemur-Eulemur-coronatus-2.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Fishing-Cat-Prionailurus-Viverrinus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Common-Brushtail-Possum-Joey-Trichosurus-Vulpecula.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Artic-Fox-Pup-Vulpes-Lagopus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Walrus-Odobenus-Rosmarus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Long-eared-Hedgehog-Hemiechinus-Auritus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Caracal-Caracal-Caracal.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Snow-Leopard-Panthera-Uncia.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Lion-Panthera-Leo.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Griffon-Vulture-Gyps-Fulvus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Mandrill-Mandrillus-Sphinx.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Gray-Wolf-Canis-Lupus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Red-Squirrel-Sciurus-Vulgaris.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/White-tailed-Deer-Odocoileus-Virginianus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Bongo-Tragelaphus-Eurycerus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Harbor-Seal-Phoca-Vitulina.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Bornean-Orangutan-Pongo-Pygmaeus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Kinkajou-Potos-Flavus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Little-Owl-Athene-Noctua.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Fennec-Fox-Vulpes-Zerda.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Ferret-Mustela-Putorius-Furo.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Veiled-Chameleon-Chamaeleo-Calyptratus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Red-Panda-Ailurus-Fulgens.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/British-Shorthair-Cat-Felis-Catus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Eastern-Grey-Kangaroo-Macropus-Giganteus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Southern-Cassowary-Casuarius-Casuarius.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Ring-tailed-Lemur-Lemur-Catta.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Pallass-Cat-Otocolobus-Manul.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Red-Kangaroo-Macropus-Rufus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Brown-throated-Sloth-Bradypus-Variegatus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Barn-Owl-Tyto-Alba.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Red-Fox-Female-Vulpes-Vulpes.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Black-Panther-Panthera-Pardus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Golden-Snub-nosed-Monkey-Rhinopithecus-Roxellana.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Koala-Phascolarctos-Cinereus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Asiatic-Elephant-Elephas-Maximus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Northern-Giraffe-Giraffa-Camelopardalis.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Giant-Panda-Ailuropoda-Melanoleuca.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Leopard-Cub-Panthera-pardus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Cheetah-Acinonyx-Jubatus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Polar-Bear-Ursus-Maritimus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Celebes-Crested-Macaque-Macaca-Nigra.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Beagle-Canis-Lupus-Familiaris.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Gerenuk-Litocranius-walleri.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/White-Rhinoceros-Ceratotherium-Simum.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Bald-Eagle-Haliaeetus-Leucocephalus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Aye-Aye-Daubentonia-Madagascariensis.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Atlantic-Puffin-Fratercula-Arctica.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Gray-handed-Night-Monkey-Aotus-Griseimembra.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Biturong-Arctictis-Binturong.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/American-Black-Bear-Ursus-Thibetanus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/European-Rabbit-Oryctolagus-Cuniculus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Common-Raccoon-Procyon-Lotor-Psora.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Ostrich-Struthio-Camelus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Zebra-Equus-Quagga.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Spectacled-Bear-Tremarctos-Ornatus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Maltese-Dog-Canis-Lupus-Familiaris.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Brown-Bear-Cub-Ursus-Arctos.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Domestic-Goat-Kid-Capra-Aegagrus-Hircus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Bengal-Tiger-Panthera-Tigris-Tigris.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Emperor-Tamarin-Saguinus-Imperator.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Spanish-Bull-Bos-Taurus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Common-Chimpanzee-Pan-Troglodytes.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Red-eyed-Tree-Frog-Agalychnis-Callidryas.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Chihuahua-Dog-Puppy-Canis-Lupus-Familiaris.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Tasmanian-Devil-Pup-Sarcophilus-Harrisii.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Pygmy-Hippopotamus-Calf-Choeropsis-Liberiensis.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/South-American-Tapir-Calf-Tapirus-Terrestris.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Wombat-Vombatus-Ursinus.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Sea-Otter-Pup-Enhydra-Lutris.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/American-Bison-Bison-Bison.jpg',
  'https://www.zooportraits.com/wp-content/uploads/2018/05/Western-Lowland-Gorilla-Gorilla-Gorilla-Gorilla.jpg'
]
# clear out all old, crusty compliments...
Compliment.destroy_all

# create new fresh compliments!
Compliment.create([
  { message: "I bet you make babies smile.", hug_count: 2, favorited: false, photo_url: zoo_portraits.sample},
  { message: "Our time together is like a nap, it never lasts long enough.", hug_count: 42, favorited: false, photo_url: zoo_portraits.sample},
  { message: "When you say, “I meant to do that,” I totally believe you.", hug_count: 3, favorited: false, photo_url: zoo_portraits.sample},
  { message: "Your eyebrows are on fleek.", hug_count: 64, favorited: false, photo_url: zoo_portraits.sample},
  { message: "You’re a great person to do a group project with.", hug_count: 2, favorited: false, photo_url: zoo_portraits.sample},
  { message: "You’re always on time to things, which is awesome because I’m not.", hug_count: 0, favorited: false, photo_url: zoo_portraits.sample},
  { message: "Looking like a complete idiot with you is really fun.", hug_count: 1, favorited: false, photo_url: zoo_portraits.sample},
  { message: "Being alone is kind of nice. Being alone with you is better.", hug_count: 64, favorited: false, photo_url: zoo_portraits.sample},
  { message: "I would hang out with you even if you hadn’t showered for a couple days.", hug_count: 0, favorited: false, photo_url: zoo_portraits.sample},
  { message: "I would go on an 18 hour road trip with you, I like you that much.", hug_count: 2, favorited: false, photo_url: zoo_portraits.sample},
  { message: "Out of all the strangers I meet on a daily basis, I’m glad you’re one of those strangers that became my friend.", hug_count: 0, favorited: false, photo_url: zoo_portraits.sample},
  { message: "You’re that “Nothing” when people ask me what I’m thinking about.", hug_count: 64, favorited: false, photo_url: zoo_portraits.sample},
  { message: "You’re more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)", hug_count: 2, favorited: false, photo_url: zoo_portraits.sample},
  { message: "I like your outfit so much that if I wore it on the same day as you I wouldn’t even be embarrassed, we’d just be that stylish.", hug_count: 66, favorited: false, photo_url: zoo_portraits.sample},
  { message: "You’re even better than a unicorn, because you’re real.", hug_count: 0, favorited: false, photo_url: zoo_portraits.sample},
  { message: "I would be really okay with you seeing me without makeup, that’s how much I like you.", hug_count: 97, favorited: false, photo_url: zoo_portraits.sample},
  { message: "You have really good taste in friends (i.e. me).", hug_count: 0, favorited: false, photo_url: zoo_portraits.sample},
  { message: "You have a really contagious laugh. See, now I’m laughing and it's all your fault.", hug_count: 83, favorited: false, photo_url: zoo_portraits.sample }
])
